#!/bin/bash

# # Source global definitions (if any)
# if [ -f /etc/bashrc ]; then
#             . /etc/bashrc   # --> Read /etc/bashrc, if present.
# fi

# set 256 color profile where possible
if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color
fi



# set 256 color profile where possible
if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color
fi

# Up-front dotfiles configuration

load_dotfiles() {
    declare -a files=(
        $HOME/.rvm/scripts/rvm # Load RVM into a shell session *as a function*
        $HOME/.dotfiles/bash/bash_options # Options
        $HOME/.dotfiles/bash/bash_exports # Exports
        $HOME/.dotfiles/bash/bash_aliases # Aliases
        $HOME/.dotfiles/bash/functions/* # Functions
        #$HOME/.dotfiles/bash/bash_prompt # Custom bash prompt
        $HOME/.dotfiles/bash/bash_paths # Path modifications
        $(brew --prefix)/etc/bash_completion # Bash completion (installed via Homebrew)
        $HOME/.bash_profile.local # Local and private settings not under version control (e.g. git credentials)
    )

    # if these files are readable, source them
    for index in ${!files[*]}
    do
        if [[ -r ${files[$index]} ]]; then
            source ${files[$index]}
        fi
    done
}

load_dotfiles
unset load_dotfiles

# GIT iTerm stuff
source ~/.git-completion.sh

# enable git unstaged indicators - set to a non-empty value
GIT_PS1_SHOWDIRTYSTATE="."

# enable showing of untracked files - set to a non-empty value
GIT_PS1_SHOWUNTRACKEDFILES="."
