#!/bin/bash
-----------------------------------
# Source global definitions (if any)
#-----------------------------------

if [ -f /etc/bashrc ]; then
            . /etc/bashrc   # --> Read /etc/bashrc, if present.
fi

# bashrc

[ -n "$PS1" ] && source ~/.bash_profile



